import { Check, ChevronLeft, Circle, Diamond, UsersRound } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ApiError, apiRequest } from '../api/client';

type Task = { key: 'post' | 'story' | 'comment'; completed: boolean; claimed: boolean; reward: number };
const names: Record<Task['key'], string> = { post: 'Опубликуйте пост', story: 'Добавьте сторис', comment: 'Напишите комментарий' };

export function EarnDiamondsPage() {
  const [tasks, setTasks] = useState<Task[]>([]); const [loading, setLoading] = useState(true); const [pending, setPending] = useState<Task['key'] | null>(null); const [error, setError] = useState<string | null>(null);
  const load = async () => { setLoading(true); try { const data = await apiRequest<{ tasks: Task[] }>('/diamonds/tasks'); setTasks(data.tasks); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Не удалось загрузить задания.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const claim = async (task: Task) => { if (!task.completed || task.claimed) return; setPending(task.key); setError(null); try { await apiRequest(`/diamonds/tasks/${task.key}/claim`, { method: 'POST' }); setTasks((items) => items.map((item) => item.key === task.key ? { ...item, claimed: true } : item)); window.dispatchEvent(new Event('diamonds-changed')); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Не удалось получить награду.'); } finally { setPending(null); } };
  return <section className="earn-page"><header className="earn-header"><Link to="/gifts" aria-label="Назад к алмазам"><ChevronLeft /></Link><div><span>Алмазы Tyson</span><h1>Заработать</h1></div></header><section className="earn-intro"><Diamond fill="currentColor" /><h2>Зарабатывайте алмазы</h2><p>Выполняйте задания, развивайте свой профиль и получайте награды в Tyson.</p></section>{error && <p className="form-error">{error}</p>}<section className="earn-section"><span>Ежедневные задания</span><h2>До 3 💎 каждый день</h2><p>Задания обновляются каждый день. Награду можно забрать после выполнения.</p>{loading ? <p className="diamond-tasks-loading">Загружаем задания…</p> : <div className="diamond-task-list">{tasks.map((task) => <article key={task.key}><div className={task.completed ? 'diamond-task-icon complete' : 'diamond-task-icon'}>{task.claimed ? <Check /> : <Circle />}</div><div><strong>{names[task.key]}</strong><small>Награда: {task.reward} 💎</small></div>{task.claimed ? <span className="diamond-task-status">Получено</span> : task.completed ? <button type="button" disabled={pending !== null} onClick={() => void claim(task)}>{pending === task.key ? '…' : 'Забрать'}</button> : <span className="diamond-task-status">Выполните</span>}</article>)}</div>}</section><section className="earn-section monetization-card"><UsersRound /><div><span>Монетизация</span><h2>Новые подписчики</h2><p>Когда на вас впервые подписывается новый человек, вы сразу получаете <strong>2 💎</strong>.</p><small>Для одной пары аккаунтов награда выдаётся только один раз — повторная отписка и подписка её не дублируют.</small></div></section></section>;
}
