import { useEffect, useState } from 'react';
import { LifeBuoy, Send, CheckCircle2 } from 'lucide-react';
import { apiRequest, ApiError } from '../api/client';

type Category = { id: string; title: string; answer: string | null };
export function SupportPage() {
  const [categories, setCategories] = useState<Category[]>([]); const [category, setCategory] = useState(''); const [question, setQuestion] = useState(''); const [answer, setAnswer] = useState<string | null>(null); const [ticketId, setTicketId] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false); const [escalated, setEscalated] = useState(false);
  useEffect(() => { void apiRequest<{ categories: Category[] }>('/support/categories').then(({ categories: next }) => setCategories(next)).catch(() => setError('Не удалось загрузить поддержку.')); }, []);
  const openTicket = async () => { if (!category || !question.trim()) return; setPending(true); setError(null); try { const result = await apiRequest<{ ticket: { id: string; cannedAnswer: string | null; status: string; visualHint: string | null } }>('/support/tickets', { method: 'POST', body: JSON.stringify({ category, question }) }); setTicketId(result.ticket.id); setAnswer(result.ticket.cannedAnswer ?? result.ticket.visualHint); if (result.ticket.status === 'open') setEscalated(true); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Не удалось создать обращение.'); } finally { setPending(false); } };
  const askAi = async () => { if (!ticketId) return; setPending(true); try { const result = await apiRequest<{ answer: string }>(`/support/tickets/${ticketId}/ask`, { method: 'POST', body: JSON.stringify({ question }) }); setAnswer(result.answer); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Tyson AI временно недоступна.'); } finally { setPending(false); } };
  const escalate = async () => { if (!ticketId) return; setPending(true); try { await apiRequest(`/support/tickets/${ticketId}/escalate`, { method: 'POST' }); setEscalated(true); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Не удалось передать обращение.'); } finally { setPending(false); } };
  const close = async () => { if (ticketId) await apiRequest(`/support/tickets/${ticketId}/close`, { method: 'POST' }).catch(() => undefined); setTicketId(null); setAnswer(null); setQuestion(''); setEscalated(false); };
  return <section className="surface-page support-page"><header className="page-heading"><div><p className="eyebrow"><LifeBuoy size={16} /> Помощь</p><h1>Поддержка Tyson</h1><p>Сначала покажем готовое решение, а если оно не поможет — подключим Tyson AI или передадим обращение владельцу.</p></div></header>{!ticketId ? <><div className="support-categories">{categories.map((item) => <button key={item.id} className={category === item.id ? 'support-category active' : 'support-category'} type="button" onClick={() => setCategory(item.id)}>{item.title}</button>)}</div><textarea className="support-textarea" value={question} onChange={(event) => setQuestion(event.target.value)} placeholder={category === 'visual' ? 'Опишите визуальный баг. Желательно приложите скриншот.' : 'Опишите вашу проблему'} maxLength={4000} /><button className="primary-button" type="button" disabled={pending || !category || !question.trim()} onClick={() => void openTicket()}><Send size={17} /> Отправить в поддержку</button></> : <div className="support-result">{answer && <div className="support-answer"><CheckCircle2 size={18} /><p>{answer}</p></div>}{escalated ? <><p>Обращение передано владельцу Tyson через Telegram. Ответ появится здесь.</p><button className="secondary-button" type="button" onClick={() => void close()}>Закрыть обращение</button></> : <div className="support-actions"><button className="primary-button" type="button" disabled={pending} onClick={() => void askAi()}>Спросить нейросеть</button><button className="secondary-button" type="button" disabled={pending} onClick={() => void escalate()}>Нейросеть не решила проблему</button><button className="text-button" type="button" onClick={() => void close()}>Закрыть</button></div>}</div>}{error && <p className="form-error">{error}</p>}</section>;
}
